

/*You are located at point (x1,y1)
 and need to travel to point (x2,y2)
. To facilitate your journey, you have three transportation options: a car, a helicopter, and walking.

This is the ordered list:

Car (Manhattan Distance): You can use your car to move in Manhattan distance, where you can only move up, down, left, or right. The Manhattan distance between two points (x1,y1)
 and (x2,y2)
 is calculated as |y2−y1|+|x2−x1|
Helicopter (Euclidean Distance): Alternatively, you have the option of using a helicopter, which moves in Euclidean distance. The Euclidean distance between the same points is calculated by (y2−y1)2+(x2−x1)2−−−−−−−−−−−−−−−−−−√
Walking (Chebyshev Distance): Finally, you can choose to walk in Chebyshev distance, where you can move up, down, left, right, or diagonally. The Chebyshev distance between the points is calculated as max(|y2−y1|,|x2−x1|)*/