/*A bookstore sells n
 different titles.

A customer may buy one of the following bundles:

A single-book bundle: choose one title and choose a format (paperback or ebook).
A double-book bundle: choose a first title and a second title (the two titles may be the same; the order matters: which one they read first), and choose a format (paperback or ebook) for the whole bundle.
Given n
, find how many different bundles a customer can order.

Input
Only one line containing n
 (1≤n≤109)
 — the number of titles.

Output*/