/*It's known that ants come out in summer to collect food for winter. Well, Ouda is sick of them.

During electricity cut off, Ouda was eating biscuits with tea and he noticed some ants gathering around his biscuits. Unfortunately for them Ouda was feeling hot and mad so he decided to trap them with some wooden sticks.

Given the coordinates of each ant, Ouda wants to trap the ants inside wooden rectangle which has area as minimum as possible. As we all know that Ouda is a kind person, so he will place the stick at most 1
 centimeter from any ant so that no ant will be under one of the rectangle's edges and got smashed.

Take a look at the examples for farther explanation.

Input
Given t
 independent testcases where (1≤t≤105
).

The first line contains n
 (1≤n≤103
) – The number of ants.

The following n
 lines contains integers xi
 and yi
 (−103≤x,y≤103
) – The coordinates for the it
h
 ant.

It is guaranteed that the sum of n
 over all test cases does not exceed 105
.

Output
One line contains the minimum possible area for the wooden rectangle.*/