

/*At a conference n
 attendees each receive a badge with a color. Two attendees form a matching pair if they have the same badge color (order doesn't matter).

You are given the sequence of badge colors (as integers, only 3 different colors are given). Compute the number of matching pairs of attendees.

Input
The first line contains an integer n
 (1≤n≤105)
 — the number of attendees.

The second line contains n
 integers c1,c2,…cn
 (1≤ci≤3
) — the color of each badge.

Output
Print a single integer — the total number of unordered matching pairs of attendees (two attendees form a pair if and only if their badge colors are equal).*/