

/*Dots had an array; he forgot its size, but he remembers that the total number of subarrays the array had was less than or equal to x
.

Given x
, print the largest possible size of the array.

A subarray is some elements of an array all next to each other; for example, all subarrays of [1,2,3]
 are: [1],[2],[3],[1,2],[2,3],[1,2,3]
.

Input
The input contains x
 (1≤x≤1017)
 — the number of subarrays of a
.

Output
Print the maximum size the array may have had.*/