

/*Mohannad needs 2
 problems to complete the contest, so he asked Dots if he knows any problems. Dots refuses to say the number of problems that he knows, but he said that there are x
 ways to choose two problems from all the problems he knows. Mohannad was able to figure out the number of problems Dots knows; can you do so as well?

Note: The test cases are guaranteed to always have a valid solution for x
.

Input
Only one line containing one integer x
 (1≤x≤1018)

Output
Print the result.*/