/*In a land full of superheros, Azzam has a strange super power. In one step, Azzam can jump x
 meters, assuming he is on point i
, he can jump into i+x
 in one step.

Azzam is currently standing on point 0
 and wants to reach point n
 in the minimum possible number of steps. A step can be :

One super jump that covers x
 meters forwards.
One normal step backwards.
Print the minimum number of steps needed to reach point n
 from point 0
.

Input
One line contains two integers n
 and x
 (1≤x,n≤109)
 – x
 can be greater than n
.

Output
Print the minimum number of steps needed to reach point n
 from point 0
.*/