


/*Given an array a
 of n
 integers, output the sum of every possible subarray that's not empty.

For example, Array a=[1,2,3]
 has subarrays:

a1,1=[1]
. Sum = 1
.
a1,2=[1,2]
. Sum = 3
.
a1,3=[1,2,3]
. Sum = 6
.
a2,2=[2]
. Sum = 2
.
a2,3=[2,3]
. Sum = 5
.
a3,3=[3]
. Sum = 3
.
Input
The first line contains a single integer n
 (1≤n≤103
) — the number of elements in the array.

The second line contains n
 integers a1,a2,…,an
 (1≤ai≤104
) — the array a
 itself.

Output
Output a sequence of n⋅(n+1)2
 elements — the sums of subarrays in order.*/